<a href="https://colab.research.google.com/github/alyssakokkatt/stats/blob/main/Jan16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python


In [ ]:
print('Welcome to Python') #This is a print statement.

Welcome to Python


##Variables and expressions


In [ ]:
a = 5                #This variable stores an int
var1= 10.0            #This variable stores a float
str_var = "Alex"      #This variable stores a string= sequence of characters

In [ ]:
type(str_var)#Lists the datatype of the variable

str

In [ ]:
num1 = 1
num2 = 3
num3 = num1/num2      #There's finite precision when it comes to floating point numbers.
num3

0.3333333333333333

In [ ]:
y = var1+a #Adding an int and a float
y


15.0

###Operators


In [ ]:
p= num1 +num2 #Addition
q = num1-num2 #Subtraction
r = num1*num2 #Multiplication
s = num1/num2 #Division
t = num1// num2 #Floor Division   #integer dividend skips floating point #Guves dividend
u = num1%num2 #Modulus, gives the remainder
v = num1**num2 #Exponent


In [ ]:
print(p,q,r,s, t, u, v)
print(" The value of p is=",p)#Old fashioned way of combing strings and variables
print(f"The value of p is {p}") #Using f-strings

4 -2 3 0.3333333333333333 0 1 1
 The value of p is= 4
The value of p is 4


###Lists

In [2]:
int_list= [1,2,3,4] #List of integers
float_list = [1.0,2.5,3.7,5.5] #List of floats
str_lists = ["a","b","c","d"] #List of strings
mixed_list = [1,2.4,"a",p] #Mixed list contaning elements of different

NameError: name 'p' is not defined

In [ ]:
mixed_list

[1, 2.4, 'a', 4]

Aggregate funcitons on lists

In [1]:
sum(int_list)#Gives sum of all elements
len(float_list)#gives count of
sum(mixed_list)

NameError: name 'int_list' is not defined

In [ ]:
int_float_list = int_list + float_list #Concatenates two lists
int_float_list

[1, 2, 3, 4, 1.0, 2.5, 3.7, 5.5]

Exercise- Calculate the avrge scores of this class

In [ ]:
scores = [65,78,30,85]
average_score = sum(scores)/len(scores)
average_score

print(f"The average score of the class is {average_score}")

The average score of the class is 64.5


In [ ]:
average_score = sum(scores)/len(scores)
max_score = max(scores) #Gives the maximum
min_score = min(scores) #Gives the minimum
print(f"The average score of the class is {average_score}, and the class highest is {max_score}, and the lowest is {min_score}")

The average score of the class is 64.5, and the class highest is 85, and the lowest is 30


###Functions and if statements

In [20]:

score =[20,30,55,78]

def has_student_passed(score):                  #define
  """
This is a multiline comment.
This function takes the score and returns pass if
the score is above 40.
  """
  if score>= 40:
    print("The student has passed the course") #Gets executed when if condition is satisfied
  else:
    print("The student has not passed the course")
  return 0
  has_student_passed(90)
  has_student_passed(25)

FOr loop

In [ ]:
for s in scores:
  print(f"s={s}")
  has_student_passed(s)


s=65
The student has passed the course
s=78
The student has passed the course
s=30
The student has not passed the course
s=85
The student has passed the course


##Homework Write a function to calculate grades and return the grade

In [16]:
def get_grade(score):
  if score >= 71 and score <= 100:
    return "A"
  elif score >= 61 and score <= 70:
    return "C"
  elif score >= 50 and score <= 60:
    return "D"
  elif score >= 40 and score < 50:
    return "E"
  else:
    return "U"
    get_grade(90)
    get_grade(55)

In [17]:
for s in scores:
  print(f"s={s}")
  get_grade(s)

NameError: name 'scores' is not defined

In [18]:
scores = [65,78,30,85]

def get_grade(score):
  if score >= 71 and score <= 100:
    return "A"
  elif score >= 61 and score <= 70:
    return "C"
  elif score >= 50 and score <= 60:
    return "D"
  elif score >= 40 and score < 50:
    return "E"
  else:
    return "U"

for s in scores:
  print(f"s={s}, Grade: {get_grade(s)}")

s=65, Grade: C
s=78, Grade: A
s=30, Grade: U
s=85, Grade: A


Getting Help

In [ ]:

help(sum) #To get help on function

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



Dictionaries

In [ ]:
# A dictionary is a data structure that does 1-1 mapping of key-value pairs
scores = [65,78,30,85]
scores_dict = {"Alex":scores[0],"nandini":scores[1],"Trusha":scores[2],"Yash":scores[3]}
scores_dict

{'Alex': 65, 'nandini': 78, 'Trusha': 30, 'Yash': 85}

Homework: (1) Use this dictionary along with the for loop to print the name and the score of the student
(2)You can also try calculating the grade of each student inside the for block.

In [23]:
scores = [65,78,30,85]
scores_dict = {"Alex":scores[0],"nandini":scores[1],"Trusha":scores[2],"Yash":scores[3]}
for name, score in scores_dict.items():
  print(f"Student: {name}, Score: {score}")
  grade = get_grade(score)
  print(f"Student: {name}, Grade: {grade}")

Student: Alex, Score: 65
Student: Alex, Grade: C
Student: nandini, Score: 78
Student: nandini, Grade: A
Student: Trusha, Score: 30
Student: Trusha, Grade: U
Student: Yash, Score: 85
Student: Yash, Grade: A


In [27]:
scores_dict.keys()#Gives all the keys (like names its a unique identifier) of the dictionary



dict_keys(['Alex', 'nandini', 'Trusha', 'Yash'])

In [28]:
scores_dict.values()#Gives all the values of the dictionary


dict_values([65, 78, 30, 85])

In [29]:
scores_dict.items()#Gives all the key-value pairs


dict_items([('Alex', 65), ('nandini', 78), ('Trusha', 30), ('Yash', 85)])

NUMPY- helps work w arrays and numerical calculations

In [30]:
import numpy as np # Importng the numpy package   #numpy is numerical python, most important library function of python

nd array in numpy-- string and numbers listable in numpy
we use numpy.array()


In [34]:
zeros_array = np.zeros(10) #An array of 10 zeros
zeros_array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
zeros_arr_int_2D = np.zeros(shape=(4,3),dtype=int) #A 2D arrays of zeros of ones
zeros_arr_int_2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
arr1 = np.ones
ones_arr = np.ones(10) #An array of 10 ones
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])           # this one only prints the last array which is why its always bets tp use the print statement.
arr1
arr2

print(f"Fist array is {arr1} and its type is {type(arr1)}")   # arr1 now it belongs to the numpy family its not just a simple list
print(f"Second array is {arr2}  and its type is {type(arr1)}")

Fist array is [1 2 3 4 5] and its type is <class 'numpy.ndarray'>
Second array is [ 6  7  8  9 10]  and its type is <class 'numpy.ndarray'>


Numpy array operations - does elemtn wise operations which is different from lists

In [ ]:
add_arr= arr1+arr2 #Adding numps arrays ;leads to element wise addition
print(add_arr)

sub_arr = arr1-arr2 #This is true for other operations as well
print(sub_arr)

mult_arr= arr1*arr2
print(mult_arr )

div_arr = arr1/arr2
print(div_arr)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

